= Document versions

Just like xref::definitions/definition-versions.adoc[definitions are versioned], documents can optionally be versioned as well.
By setting the `versionable` property on a `DynamicDocument` to `true`, modifications to a document will result in a new version being created.
This allows a single document to be linked to various definition versions or various documents for the same definition to link to different definition versions.
Each document also has a backlink to its latest version for easy access.

Document versions hold the content of the document and link to the definition version that holds the structure of when the document was created or last modified.

NOTE: The content of a document is persisted through `DynamicDocumentVersion` s.
This means that at least one version will be present if a document contains data.

== Default interface

Documents created through the interface are versioned by default.
When modifying a document, a new version will be created based on the latest version of the linked definition.
This means that when the content of a document is modified, a new version will automatically be created.

For versioned documents, a `history` tab is also provided through which older versions of the document can be viewed.

== Creating a document version

See xref::working-with-documents/using-documents-in-code.adoc[Working with documents] for more information on how to create new documents, modify an existing document (version) or creating a new version for a document.