= Creating a view definition

== Defining views

A dynamic view consist of a number of properties that should be rendered on a specific view.
A dynamic view is registered for a specific xref:definitions/create-a-view-definition.adoc[dynamic document] through a parent-child relationship, where the document definition is the parent of the view definition.
Depending on the view type, additional configuration options may be available, for example on a <<defining-list-views,list view>>, filter controls may be defined.

A single definition requires at least

a name ::
The `name` defines on which view the definition will be applied.
E.g. a definition with name `my-custom-view` would be applied on a view with name `my-custom-view`.

a type ::
 The `type` defines on views of which type the definition will be applied.
 E.g. a definition with type `list` would be applied only on list view configurations.

a list of properties ::
 The list of properties is a listing of the properties of the parent document that should be rendered on the view.

a parent document definition ::
 A view definition always configures views for a specific document.

The combination of `name` and `type` must be unique in the scope of its parent, as only one view configuration can be applied to a specific view.

[[defining-list-views]]
=== Defining list views

To configure a xref:entity-module:building-views/list-view.adoc[list view] for a document, a view definition will be created with the type `list`.
Specifically on a list view, xref:entity-module:entity-query/filtering-list-views.adoc[filter controls] can be configured.

.Example list view definition
[source,yaml]
----
view-definition: # <1>
  name: listView # <2>
  type: list # <3>
  properties: # <4>
    - "versionLabel"
    - "field:name"
  filter: # <5>
    mode: # <6>
      advanced: true
    fields: # <7>
      - id: field:name
----

<1> View definitions always start with the root path `view-definition`.
<2> The default list view that is rendered has the name `listView`.
<3> To configure list views, the `type` must be list.
<4> The properties that should be rendered are listed.
DynamicDocument properties can be listed as well as document definition properties.
Document definition properties must be prefixed with `field:`.
<5> A filter configuration is defined.
<6> The filter control modes are defined.
<7> A field is specified for which a filter control should be rendered.

Below is a listing of all filter options that are available.

.Example list view definition
[source,yaml]
----
view-definition:
  name: listView
  type: list
  properties:
    - "field:singular"
    - "field:multiple"
  filter:
    mode:
      basic: true # <1>
      advanced: true # <2>
    defaultSelector: MULTI # <3>
    defaultQuery: "order by field:singular asc" # <4>
    basePredicate: "field:multiple contains ('something')" # <5>
    fields:
      - id: field:singular # <6>
        selector: SINGLE
        operand: NEQ
      - id: field:multiple # <7>
----
<1> Basic filter controls should be rendered.
This option defaults to true if at least one field is defined.
<2> The advanced EQL filer control should be rendered. Defaults to false
<3> The default selector for controls. Defaults to SINGLE.
<4> The default query that should *always* be applied.
<5> The base predicate that provides the initial filtering.
<6> A configuration for a field that should have a single selectable option with a specific operand.
<7> A configuration for a field that uses defaults.
This field will have `MULTI` as a selector and will receive a default operand.

=== Defining form views
