= Creating a custom type definition

It is possible to create a custom field type inside your document definition.
Other fields in the document definition can reference that field type.

A custom type definition is almost exactly like a regular field definition, with the exception of defining a `base-type` key instead of a `type` key.
The id of a custom type can be used by other fields as the value of field `type`.

.Example defining and using custom types
[source,yaml]
----
document-definition:
  name: person
  types:
    - id: country # <1>
      base-type: string
      possible-values:
        - BE
        - NL
    - id: address # <1>
      base-type: fieldset
      fields:
        - id: street-name
          type: string
        - id: street-nr
          type: number
        - id: city
          type: string
        - id: country
          type: country # <2>
  content:
    - id: firstname
      type: string
    - id: lastname
      type: string
    - id: home-address
      type: address # <2>
    - id: work-address
      type: address # <2>
----

<1> Custom type definitions.
<2> Using custom types as field type.

In our example the `address` custom type in turn defines a field using the `country` custom type.

A custom type behaves as a sort of template definition for a field.
The options defined on the type definition can often be extended by the same options on the implementing field.

The following rules apply:

* Any `possible-values` defined on a field, will *replace* the `possible-values` from the custom type.
* Any xref:validators/index.adoc[validators] defined on the field will be added to the ones attached to the custom type; for that particular field.
* Any xref:definitions/creating-a-document-definition.adoc#_configure_ui_messages[messages] defined on the field will replace the same message codes from the custom type.
All other messages defined both on the field or the custom type will be available.
* When dealing with fieldset: any `fields` defined on the field will be *added after* the ones defined on the custom type.

These rules cascade: if you have a custom field type that uses another custom type as `base-type`, all definitions will be merged according to the rules described above.