[[defining-list-views]]
= Document list view

A list view configures the list overview page of a document type.
This builds on top of the xref:entity-module::building-views/list-view.adoc[EntityModule list view].

A list view for a document type can be configured by adding a view definition with type `list` and the name `listView`.
On a list view, properties to render as well as xref:entity-module::entity-query/filtering-list-views.adoc[filter controls] can be configured.

== General configuration

.Example list view definition
[source,yaml]
----
view-definition: # <1>
  name: listView # <2>
  type: list # <3>
  properties: # <4>
    - "versionLabel"
    - "field:name"
  filter: # <5>
    mode: # <6>
      advanced: true
    fields: # <7>
      - id: field:name
      - id: field:status
        selector: MULTI <8>
----

<1> View definitions always start with the root path `view-definition`.
<2> The default list view that is rendered has the name `listView`.
<3> To configure list views, the `type` must be list.
<4> The properties that should be rendered are listed.
DynamicDocument properties can be listed as well as document definition properties.
Document definition properties must be prefixed with `field:`.
<5> A filter configuration is defined.
<6> The filter control modes are defined.
<7> A field is specified for which a filter control should be rendered.
<8> Allow multiple values to be selected in the filter control

.Listing of available properties on a filter configuration
[cols="1,1,2", options="header"]
|===
|property |required |description

|mode
|optional
|Allows for the definition of which filter control modes should be available.
By default the `basic` mode will be shown if at least one field is configured.
`advanced` mode will by default not be available.

A specific mode can be set by setting the mode to true, e.g. `advanced: true`

|defaultSelector
|optional
|Sets the default selector that should be used for all specified fields, if no selector is provided for the field itself.
Defauls to `SINGLE`.

|defaultQuery
|optional
|Sets the query that should be executed on every request.
The provided query is an xref:entity-module::entity-query/eql.adoc[EQL statement].

|basePredicate
|optional
|Sets the query that provides the initial filtering when navigating to the view.
The provided query is an xref:entity-module::entity-query/eql.adoc[EQL statement].

|fields
|optional
|Defines for which fields an xref:entity-module::entity-query/filtering-list-views.adoc[EQL filter control] should be rendered.
Listed fields must always specify an `id` and can override the `selector` and `operand` that should be used.
The `selector` property can be set to `SINGLE` or `MULTI` (`SINGLE` by default).
For the `operand` options refer to the javadoc of `EntityQueryOps`.
|===

== List summary view

If a view definition called `listSummaryView` is present, the list view will also provide a summary view.
The interface will be adjusted to allow expanding of a row and seeing the result of the summary view.

See the xref:definitions/list-summary-view.adoc[separate section] for more details.