= Dynamic field types

A dynamic document field definition requires a specific field type.
The field type determines how the field value is handled, displayed and stored.

A field type usually corresponds with a specific Java type.

== Example

The following is an example with both simple fields and custom field types.

[source,yaml]
----
document-definition:
  name: person
  types:
    - id: street-name
      base-type: string
    - id: address
      base-type: fieldset
      fields:
        - id: street-name
          type: street-name
        - id: street-nr
          type: number
        - id: zipcode
          type: number
    - id: company
      base-type: fieldset
      fields:
        - id: name
          type: string
          label: Name
          text:
            description: Public company name
        - id: activities
          type: string[]
          possible-values:
            - building-software
            - selling-cars
            - destroying-houses
        - id: founded
          type: date
        - id: operational
          type: boolean
        - id: shareholders
          type: string
          possible-values:
            - private
            - public
  content:
    - id: firstname
      type: string
    - id: lastname
      type: string
    - id: phone-number
      type: string
    - id: email
      type: string
    - id: description
      type: text
    - id: address
      type: address
    - id: company
      type: company
----

== Default type keys

The following type keys (for use in `type` or `base-type`) are available:

[cols="1,1,3"]
|===
|Type key |Field type |Description

|`string`
|xref:field-types/string.adoc[Strings]
|Single-line text.

|`text`
|xref:field-types/string.adoc[Strings]
|Multi-line text.

|`number`
|xref:field-types/number.adoc[Numbers]
|Whole number (`Long`). Ranges from -9223372036854775808 to 9223372036854775807.

|`number(byte)`
|xref:field-types/number.adoc[Numbers]
|Whole number (`Byte`). Ranges from -128 to 127.

|`number(short)`
|xref:field-types/number.adoc[Numbers]
|Whole number (`Short`). Ranges from -32768 to 32767.

|`number(integer)`
|xref:field-types/number.adoc[Numbers]
|Whole number (`Integer`). Ranges from -2147483648 to 2147483647.

|`decimal`
|xref:field-types/number.adoc[Numbers]
|Floating point number (`BigDecimal`). Unbounded precision.

|`decimal(2)`
|xref:field-types/number.adoc[Numbers]
|Floating point number (`BigDecimal`). Two decimal points precision.

|`boolean`
|xref:field-types/boolean.adoc[Boolean]
|Boolean (`true`/`false`) value.

|`fieldset`
|xref:field-types/fieldset.adoc[Fieldset]
|Collection of nested fields.

|`@entity`
|xref:field-types/linked-entity.adoc[Linked entity]
|Linked entity field (for example a `User`).

|===

== Enumerations

Several base types can be turned into an enumeration by specifying the `possible-values`.
See the xref:field-types/enumeration.adoc[separate page] for more information.

== Custom types

The example shows the use of custom field types.
The chapter on xref:definitions/creating-a-type-definition.adoc[creating a custom type] gives more information on how to to this.