= Extending definition types

Next to the base types that are provided, which are `document` and `view`, it is also possible to create your own definition types.
A definition type represents the data structure which its definition instances must uphold.


== Defining types

Creating a definition type requires both a raw definition and an actual definition.
The raw definition of a type is the converted value of json (or yaml) to a typed object.
During conversion no validation will occur and as such, invalid content may be correctly parsed.

Using raw definitions as the definition object to work with is not advised.
It is preferred to create a separate object that fully represents a validated definition of your custom type.
Once the raw definition and the actual definition are created, a type configuration has to be registered on the `DefinitionTypeConfigurationRegistry`

=== Raw Definition

Before a definition is created, a raw definition will be made.
A raw definition is simply a typed object converted from a given json/yaml and must implement the `RawDefinition` marker interface.
A raw definition can hold anything and is not validated as to whether it is the correct format.

.Example raw definition
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonRootName("view-definition")
public class RawViewDefinition implements Serializable, RawDefinition
{
	private String name;
	private String type;

	@JsonDeserialize(as = ArrayList.class, contentAs = String.class)
	@Singular("property")
	@NonNull
	private List<String> properties = new ArrayList<>();

	public List<String> getProperties() {
		return properties != null ? properties : Collections.emptyList();
	}

	public static RawViewDefinition copyOf( @NonNull RawViewDefinition definition ) {
		return SerializationUtils.clone( definition );
	}
}
----

==== Validation

A custom `Validator` object can be registered on the `DynamicDefinitionTypeConfiguration` of your type to validate its `RawDefinition` instances.

=== Registering on the registry

Definitions can be converted to and from raw definitions using the `RawDefinitionService`.
To allow a custom type to be converted by the `RawDefinitionService`, a configuration must be registered on the `DynamicDefinitionTypeConfigurationRegistry`
A configuration can be created by registering the type information on the registry.

.Type configuration information of a DefinitionType
[cols="1,2",opts=header]
|===
|Name |Description

|Name
|The name of the type being registered.
E.g. document for the Document type.

|Raw definition
|The raw definition type to and from which the json representation must be converted.
The raw definition type must implement the `RawDefinition` interface.

|Validator
|The validator that should be used to validate the raw definition.
If the raw definition is successfully validated, an actual definition can be created.
|===

.Example registration of a definition type.
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
    @Autowired
    public void registerBaseTypes( DynamicDefinitionTypeConfigurationRegistry typeConfigurationRegistry ) {
        typeConfigurationRegistry.register( DynamicDefinitionType.VIEW, RawViewDefinition.class, rawViewDefinitionValidator );
    }
----

After registering the configuration, a `DynamicDefinitionTypeConfiguration` will be created and returned, which holds the provided parameters, as well as the actual type instance.

// TODO: definition instance of a definition type configuration
////
=== The Actual Definition
...
////

